// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1kSyNndizkqJwVqnUoB94zXFP7Ujgb_k',
    appId: '1:714008099387:web:446fb38b7f5131b9743a1e',
    messagingSenderId: '714008099387',
    projectId: 'whirl-wash',
    authDomain: 'whirl-wash.firebaseapp.com',
    storageBucket: 'whirl-wash.firebasestorage.app',
    measurementId: 'G-Z34EK04EZG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqalcLCdVaRti1T3412H6nwkqTso-xpVw',
    appId: '1:714008099387:android:9738d007f63e0e31743a1e',
    messagingSenderId: '714008099387',
    projectId: 'whirl-wash',
    storageBucket: 'whirl-wash.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCleQcsbGNhfRU9cvpAs7SqtZVoXAy3q2E',
    appId: '1:714008099387:ios:7f90a7423200041f743a1e',
    messagingSenderId: '714008099387',
    projectId: 'whirl-wash',
    storageBucket: 'whirl-wash.firebasestorage.app',
    iosBundleId: 'com.example.whirlWash',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCleQcsbGNhfRU9cvpAs7SqtZVoXAy3q2E',
    appId: '1:714008099387:ios:7f90a7423200041f743a1e',
    messagingSenderId: '714008099387',
    projectId: 'whirl-wash',
    storageBucket: 'whirl-wash.firebasestorage.app',
    iosBundleId: 'com.example.whirlWash',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1kSyNndizkqJwVqnUoB94zXFP7Ujgb_k',
    appId: '1:714008099387:web:c4b218f872bc5656743a1e',
    messagingSenderId: '714008099387',
    projectId: 'whirl-wash',
    authDomain: 'whirl-wash.firebaseapp.com',
    storageBucket: 'whirl-wash.firebasestorage.app',
    measurementId: 'G-WRWC1FQ3L5',
  );
}
